lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: [Esteban Marquer]
description: [A presentation, CV, and home page for and by Esteban Marquer]

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
theme: jekyll-theme-leap-day
